spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://localhost:3306/coursedb
    username: root
    password: XXXXXXXXX
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082


