spring:
  application:
    name: author-service
  datasource:
    url: jdbc:mysql://localhost:3306/authordb
    username: root
    password: XXXXXXX
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083


